### ISSUE TITLE
Incoming TCP packet delay from client

### ISSUE THREAD

**Issue by yeeapple** [EsotericSoftware/kryonet#100]
http://stackoverflow.com/questions/31499965/how-can-tcp-packet-be-delayed-in-client-server-model I use KryoNet 2.21 version.

**Comment by yeeapple** [comment]
Fixed by recompiling Server.java with disabled Nagle. Keep in mind that it is enabled by default.

**Comment by NathanSweet** [comment]
It's disabled in TcpConnection. What did you change?

**Comment by yeeapple** [comment]
That trick did not work. I have tried to call setOption in Server.java but somehow I missed that I was using different JAR file. Anyway, there is delay in incoming packets. I have no idea what to do.

**Comment by NathanSweet** [comment]
You might try different Android devices. Android is known for being junk.

**Comment by yeeapple** [comment]
I found that it worked pretty well on LG phone. There were only a few hiccups at start. What I believe that there are some problems with Huawei Y300 phone because sent packets are stacked and delayed at that point.

**Comment by NathanSweet** [comment]
Sounds like Android. Doubt anything can be done, sorry!

**Comment by yeeapple** [comment]
After a lot of tests I have figured out the problem was optimization. As I am trying to create heavy application with screen rendering at 30 FPS, calculating things and intensively receiving information from the network. The solution was to use more threads, synchronize everything and minimize slow block of code. Still I haven't tested how does GC react to big objects (~1 MB) received from network.
