### ISSUE TITLE
Does this sever applicable good for client write in c/c++

### ISSUE THREAD

**Issue by baiydavid** [EsotericSoftware/kryonet#101]
if client is written in c/c++, and tcp body is byte[]  in binary bytes,  this server can work well??
thanks.

**Comment by baiydavid** [comment]
KryoNet makes the assumptions that it will only be used for client/server architectures and that KryoNet will be used on both sides of the network. Because KryoNet solves a specific problem, the KryoNet API can do so very elegantly.

what does this mean when client is written in c language

**Comment by NathanSweet** [comment]
The protocol is encoded in Java class files. It will be very difficult to
read Kryo data from another language, unless you send only simply data
types.

**Comment by baiydavid** [comment]
I want to find a TCP Server package,  easy to use,  send byte stream in both server and client,   and recv the data according to user define structure  with my own codes.  
Do you have any suggestions?  Thanks.

**Comment by NathanSweet** [comment]
Please use the mailing list for discussion, this is an issue tracker.
