### ISSUE TITLE
No serialization/deserialization, just send/receive chars?

### ISSUE THREAD

**Issue by Wulf** [EsotericSoftware/kryonet#110]
Hi, I'd like to use kryonet to send/receive chars between a Java server and a node.js client.

I'm thinking this is possible if I create my own Serialization implementation or even JsonSerialization! Correct me if I'm wrong?

Label: Question.

**Comment by DevCubeHD** [comment]
I like you idea.. Just use netty or send Strings with kryonet

**Comment by Wulf** [comment]
Yeah the sending party wasn't hard, what made it difficult was stopping the connection from closing because the nodejs client didn't send keepAlive packets which the kryonet server was expecting. 

I tried faking the keepAlice packet by sending a string "alive" from the client to the server and then have the server create a keepAlive packets and register it for the client, but that felt too hacky and it ended up not working anyway.

I had to abandon kryonet and just use websockets.
