### ISSUE TITLE
Listener#doesAccept(Object) to prevent endless list of instanceof checks?

### ISSUE THREAD

**Issue by Isfirs** [EsotericSoftware/kryonet#130]
Isn't it a better way to ask the `listener` if it may accept the Object by calling a `Listener#doesAccept(Object):bool`  or `Listener#doesAccept(Class):bool`? (I don't care the actual name, but I prefer the `class` variant).

**Comment by NathanSweet** [comment]
No, such a method would have to do the logic to see if it can accept the object, return a boolean, then `received` would be called and that same logic would need to be done again. A listener does not need to use a list of instanceof checks, it can use a HashSet<Class> or any other technique it wants. If you have a large number of types, you could use a wrapper with an int or enum, eg:
```
switch (wrapper.type) {
case something:
    YourClass object = (YourClass)wrapper.object;
    break;
}
```
