### ISSUE TITLE
use kryonet in ios

### ISSUE THREAD

**Issue by mahdiyousofun** [EsotericSoftware/kryonet#147]
i wrote an application used this library for android , the server and client written by java.
but i dont know how can i create client in ios
how can i use this library in ios?

**Comment by Vacster** [comment]
This question is answered in the following thread: https://github.com/EsotericSoftware/kryonet/issues/54

They recommend frameworks which allow Java in iOS, like RoboVM - which is closed now unforunately. A list of frameworks available given here: https://stackoverflow.com/a/23232007
