### ISSUE TITLE
Large buffer to server

### ISSUE THREAD

**Issue by wlkjlc** [EsotericSoftware/kryonet#148]
The Client class is created each time transmission is done, and it is possible to set the buffer according to the context. However, since the Server class is always active, you need to have a buffer that matches the largest possible message. If you set a huge buffer to Server, is there performance loss when processing small messages? Should I separate Server with huge messages and small messages if so?

**Comment by NathanSweet** [comment]
Setting a large buffer doesn't hurt performance, it just uses more memory.

Note the mailing list is better for discussion.
