### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by cpbentley** [EsotericSoftware/kryonet#154]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.esotericsoftware.reflectasm.AccessClassLoader (file:/Users/student5309/Java/kryonet-2.21/jars/production/onejar/kryonet-2.21-all.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.esotericsoftware.reflectasm.AccessClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

I got this when running Chat client/server example

Eclipse/Java 8/kryonet 2.21 production

**Comment by lewisxy** [comment]
Same issue, IntelliJ/Java 10/MacOS/kryonet 2.21 production

**Comment by jopiortiz** [comment]
Same issue, IntelliJ/Java 12/MacOS/kryonet 2.21 production

**Comment by theonlypowerranger** [comment]
Happened to me as well and whilst the request to the server got thru, the server's response never reaches the client.
java 11 ubuntu

**Comment by coopsmoss** [comment]
I also get this, java 11, ubuntu, V 2.22.0-RC1

**Comment by NathanSweet** [comment]
Kryo uses unsafe operations. This is normal. If you hate the messages, you can use a workaround from here:
https://github.com/EsotericSoftware/kryo/issues/692#issuecomment-595292219

**Comment by TomaszGaweda** [comment]
In some time usage of Unsafe will be totally prohibited. IMHO rather than ignoring the issue it would be better to have it at least open, so that people can track changes that have to be implemented in future
