### ISSUE TITLE
Mavenize kryonet

### ISSUE THREAD

**Issue by ghost** [EsotericSoftware/kryonet#38]
_From [robin.ki...@gmail.com](https://code.google.com/u/114916895304570456707/) on August 22, 2013 19:13:56_

<b>What steps will reproduce the problem?</b>
1. Look for kryonet on maven central&#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
Expected to find kryonet on maven central.  It's not.&#13;
&#13;
<b>What version of the product are you using? On what operating system?</b>
&#13;
&#13;
<b>Please provide any additional information below.</b>
See this link for a mavenization of kryonet that works in my local environment.&#13;
<a href="https://github.com/esialb/kryonet-mavenized/commit/7cf21528be35e0a1c4f7eef682e8dd406209f2f9" rel="nofollow">https://github.com/esialb/kryonet-mavenized/commit/7cf21528be35e0a1c4f7eef682e8dd406209f2f9</a>

_Original issue: http://code.google.com/p/kryonet/issues/detail?id=37_

**Comment by sreich** [comment]
this issue is solved, could someone please close this?
