### ISSUE TITLE
kryonet protocol

### ISSUE THREAD

**Issue by sanjeev909** [EsotericSoftware/kryonet#56]
Hi,

As I dig deeper into the kryonet/kryo libraries, I appreciate the power and simplicity of the framework. Amazing work folks.

I'm trying to serialize cocoa-objects over a socket connection to kryonet server. The server is correctly matching the source class to registered class and completing the serialization at the server end.

I'm almost there, but for the following issues - 

1. The first field in the source is getting serialized to second, the second(source) to third (destination) and so-on. 

2. Strings are not getting serialized correctly because I'm not specifying the format (ascii/utf8) in the buffer. How is this done?

Will appreciate if you can point to the protocol elements to be inserted in the buffer.

Regards
Sanjeev

**Comment by sreich** [comment]
could we close this issue if it is no longer needed?
