### ISSUE TITLE
kryonet update latest jar

### ISSUE THREAD

**Issue by erickga** [EsotericSoftware/kryonet#62]
Hi, I´ve been using the Kryonet2.21 library for an android project and I ´ve realized that there has been some new changes to this version (like ClientDiscoveryHandler.java and so on) 
I´ve downloaded the new project version but I cant make it run.. I keep getting a NoClassDefError when calling Server.class and I am pretty sure is because I am not building correctly the library Jar..   how can I build it so that I get a OneJar file?? (like in kryonet2.21)??  or is there some place where I can dowload it ??
thanks

**Comment by sreich** [comment]
could you close this issue, given you've solved it.
