### ISSUE TITLE
Connected, but timed out during TCP registration. Note: Client#update must be called in a separate thread during connect

### ISSUE THREAD

**Issue by mubbashar** [EsotericSoftware/kryonet#69]
I am using this library in my android. 

socketsingletonObj.start();
Kryo kryo = socketsingletonObj.getKryo();
InetAddress serverAddr = InetAddress.getByName(Helper.serverIpAddress);
socketsingletonObj.connect(5000, serverAddr,Helper.serverPort);

why i am getting this error. 

while if i use simple socket it works fine like this 

InetAddress serverAddr = InetAddress.getByName(Helper.serverIpAddress);
socket = new Socket(serverAddr, Helper.serverPort);

it works fine. so should i use simple socket instead of this ?

**Comment by voidstarfire** [comment]
I have the same issue (http://stackoverflow.com/questions/32537154/connecting-socket-io-and-kryonet-connected-but-timed-out-during-tcp-registrati)

Anyone if this would be fixed or not?

**Comment by MoshDev** [comment]
I had the same issue, I fixed it that I forgot to call client.start() before connecting:
`client.start();`
`client.connect(...)`

**Comment by Darkyenus** [comment]
KryoNet client can only connect to KryoNet server, due to some initialization packets that need to be transferred, as mentioned. It is not possible to disable this behavior easily and without some digging in the code, because there is a few more (useful) packets that must be handled by both server and client (such as KeepAlive).

**Comment by anubiann00b** [comment]
To summarize, you can only connect a Kryonet client to a Kryonet server, and you need to call `client.start();` before `client.connect(...)`. This issue should be closed.

**Comment by voidstarfire** [comment]
To summarize limitations
- You cannot connect to any other socket IO provider/draft, Kryonet only works with its-self.
- You must call connect & start in a separate thread and never the UI thread. (Remember to postBack)
- With RoboVM you will need to mark specific classes as unobfuscated.
- ^^ You will also need to mark these classes unobfuscated with pro-guard.

**Comment by benlarsendk** [comment]
Well. I still have this problem. 
It's working fine between some clients, and not so fine between other. 

```
new Thread(()->{
            Client client;
            System.out.println("Initializing TV Client");
            Log.set(Log.LEVEL_TRACE);
            client = new Client();
            Kryo kryo = client.getKryo();
            kryo.register(RegistrationRequest.class);
            try {
                client.start();
                client.connect(5000, "hgwstress.homeip.net", 6010,6010);
            } catch (IOException e) {
                System.out.println("Not able to connect to TV Controller");
            }


            RegistrationRequest registrationRequest = new RegistrationRequest();
            registrationRequest.name = "Gunnar";
            registrationRequest.mac = "123";

            try {
                Thread.sleep(2500);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            client.sendTCP(registrationRequest);

            while(true)
            {}

        }).start();

```


This for example will crash when the registrationrequest is send. And yes, it is registered on the server.

**Comment by sandro-csimas** [comment]
The same here, any news?

**Comment by benlarsendk** [comment]
@sandro-csimas 
It seems like i might be some order-problems. I got my TV-client working: 

`public class TVClient implements IClient {
    com.esotericsoftware.kryonet.Client client;
    Object lock = new Object();

    public boolean connected = false;

    public TVClient() {
        System.out.println("Initializing TV Client");
        Log.set(Log.LEVEL_WARN);
        client = new Client(256000, 256000);
        client.start();
        try {
            client.connect(5000, "hgwstress.homeip.net", 4450);
            connected = true;
        } catch (IOException e) {
            System.out.println(e.getMessage());
            System.out.println("Not able to connect to TV Controller");
        }
        Kryo kryo = client.getKryo();
        kryo.register(TVRequest.class);
        kryo.register(StateRequest.class);



        client.addListener(new Listener() {
            public void received(Connection c, Object object) {
                if (object instanceof StateRequest) {
                    System.out.println("Got state");
                    StateRequest request = (StateRequest) object;
                    StateRegister.getRegister().setTVControllerStatus(request.Ready);
                }
            }
        });    }


        @Override
        public void reconnect(){
            try {
                System.out.println("Reconnecting in 5 seconds....");
                try {
                    Thread.sleep(5000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                client.reconnect();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

    public void TransmitRequest(IRequest request) {
        synchronized (lock) {
            client.sendTCP(request);

        }
    }
}
`

**Comment by NathanSweet** [comment]
There doesn't seem to be an issue here. The OP's problem was that `start` was not called before `connect`. This issue seems to be resolved. Others later say they get a crash at some point, but don't post the crash. Others say they have a problem, but no executable example code is provided. Please consider posting a new issue with an SSCCE. http://sscce.org/

**Comment by masecla22** [comment]
Even though this is closed, I will leave a quick comment on how I solved my issue. I called `start` before `connect` and did everything in this thread. My problem, however, ended up being that a config was somehow being read wrong, and setting the timeout to 0. If you set the timeout to 0, you will end up with a `Connected, but timed out during TCP registration.`, so you should also double check that.
